version: "3"
services:
  reverse-proxy:
    build:
      context: .
      dockerfile: ./reverse-proxy.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - order-beverage-service

  order-beverage-service:
    build:
      context: .
      dockerfile: ./order-beverage-service.Dockerfile
    depends_on:
      - weather-service
      - beverage-preference-service

  weather-service:
    build:
      context: .
      dockerfile: ./weather-service.Dockerfile
    ports:
      - "9091:9091" # 暴露端口，方便直接测试
    environment:
      FLASK_APP: weather_service.py

  beverage-preference-service:
    build:
      context: .
      dockerfile: ./beverage-preference-service.Dockerfile
    environment:
      FLASK_APP: beverage_preference_service.py
